### Numpy 

Numpy : Numerical Python

Advantages of Numpy Arrays:

    1. Allows several Mathematical operations
    2. Faster operations

In [1]:
import numpy as np

In [27]:
# Create numpy array
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


#### List vs Numpy - Time Taken

In [28]:
from time import process_time

#### Time taken by list

we will take a list of numbers and add 5 to each and every number present inside the list

In [29]:
python_list = [i for i in range(10000000)]

start_time = process_time()

#Adding the value
python_list = [i+5 for i in python_list] 

end_time = process_time()

# Time taken by the process to complete
print("Total time taken : ",end_time - start_time)

Total time taken :  0.859375


#### Time taken by Numpy Array

In [30]:
np_array = np.array([i for i in range(10000000)])

start_time = process_time()

np_array += 5 # np_array = np_array + 5

end_time = process_time()

print("Total time taken : ", end_time - start_time)

Total time taken :  0.0


Numpy Arrays

In [31]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [32]:
# array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [33]:

# Creating a 1-D array
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [34]:
# Creating a 2-D array
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b.shape # rows x columns

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [35]:
# Creating a 3-D array
c = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(c)
c.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [36]:
# Creating array with floating point values
d = np.array([[1,2,3],[4,5,6]],dtype=float)
print(d)

[[1. 2. 3.]
 [4. 5. 6.]]


Initial placeholders in numpy arrays

In [37]:
# Create numpy array of zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
# create numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [39]:
# array of a particular value
z = np.full((5,4),5) #np.full((rows x columns), value)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [42]:
# create identity matrix : all diagonal value will be 1 and other 0
# in identity matrix the number of rows and columns are always equal
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [44]:
# create numpy array with random values
# values will be between 0 to 1
b = np.random.random((3,4))
print(b)

[[0.18482578 0.63765263 0.10150314 0.13397682]
 [0.72465007 0.98802471 0.39990904 0.02203821]
 [0.84789414 0.36008288 0.88656573 0.19100654]]


In [46]:
# random value array : integers within a specific range
c = np.random.randint(10,100,(4,6)) # np.random.randint(range,(rows x columns))
print(c)


[[91 25 53 57 73 92]
 [45 11 93 38 94 98]
 [56 28 16 58 68 71]
 [92 27 61 66 98 87]]


In [ ]:
# Array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,6) #np.linspace(start, end, no. of values i need)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# Array of evenly spaced values --> specifying the step
# number of steps to skip
e = np.arange(10,30,6)
print(e)

[10 16 22 28]


Convert a list to Numpy array

In [54]:
# similarly tuple can be created to a numpy array
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

#### Analysing a numpy array

getting insides from an array and getting information


In [55]:
c = np.random.randint(10,90,(5,5))
print(c)

[[84 50 89 15 44]
 [22 21 76 32 24]
 [49 38 82 86 84]
 [25 32 35 10 17]
 [58 85 79 55 34]]


In [56]:
# Array dimension
print(c.shape)

(5, 5)


In [57]:
# number of dimension
print(c.ndim)

2


In [58]:
# number of elements in an array
print(c.size)

25


In [59]:
# checking the datatype of the values in the array
print(c.dtype)

int32


Mathematical operations on a np array

In [ ]:
# addition on list 
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # it will concatenate the list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [66]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)


[[1 5 5]
 [2 0 3]
 [0 7 4]]
[[11 14 19]
 [11 17 15]
 [16 18 18]]


In [ ]:
# Numpy element wise operations
print("Addition")
print(a + b)
print("Subtraction")
print(a-b)
print("Multiplication")
print(a*b)
print("Division")
print(a/b)

Addition
[[12 19 24]
 [13 17 18]
 [16 25 22]]
Subtraction
[[-10  -9 -14]
 [ -9 -17 -12]
 [-16 -11 -14]]
Multiplication
[[ 11  70  95]
 [ 22   0  45]
 [  0 126  72]]
Division
[[0.09090909 0.35714286 0.26315789]
 [0.18181818 0.         0.2       ]
 [0.         0.38888889 0.22222222]]


In [70]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

[[0 8 4]
 [1 0 2]
 [6 7 2]]
[[16 11 18]
 [10 14 17]
 [17 15 14]]


In [71]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[16 19 22]
 [11 14 19]
 [23 22 16]]
[[-16  -3 -14]
 [ -9 -14 -15]
 [-11  -8 -12]]
[[  0  88  72]
 [ 10   0  34]
 [102 105  28]]
[[0.         0.72727273 0.22222222]
 [0.1        0.         0.11764706]
 [0.35294118 0.46666667 0.14285714]]


Array Manipulation

In [72]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 2 4]
 [1 5 5]]
(2, 3)


In [73]:
# Transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 1]
 [2 5]
 [4 5]]
(3, 2)


In [74]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 4 7]
 [0 0 0]]
(2, 3)


In [75]:
# Another method for transpose
trans2 = array.T
print(trans2)
print(trans2.shape)

[[5 0]
 [4 0]
 [7 0]]
(3, 2)


In [77]:
# Re-shaping the array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 2 4]
 [3 1 4]]
(2, 3)


In [79]:
b = a.reshape(3,2)
print(b)

[[8 2]
 [4 3]
 [1 4]]
