### Numpy 

Numpy : Numerical Python

Advantages of Numpy Arrays:

    1. Allows several Mathematical operations
    2. Faster operations

In [1]:
import numpy as np

In [27]:
# Create numpy array
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


#### List vs Numpy - Time Taken

In [28]:
from time import process_time

#### Time taken by list

we will take a list of numbers and add 5 to each and every number present inside the list

In [29]:
python_list = [i for i in range(10000000)]

start_time = process_time()

#Adding the value
python_list = [i+5 for i in python_list] 

end_time = process_time()

# Time taken by the process to complete
print("Total time taken : ",end_time - start_time)

Total time taken :  0.859375


#### Time taken by Numpy Array

In [30]:
np_array = np.array([i for i in range(10000000)])

start_time = process_time()

np_array += 5 # np_array = np_array + 5

end_time = process_time()

print("Total time taken : ", end_time - start_time)

Total time taken :  0.0


Numpy Arrays

In [31]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [32]:
# array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [33]:

# Creating a 1-D array
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [34]:
# Creating a 2-D array
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b.shape # rows x columns

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [35]:
# Creating a 3-D array
c = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(c)
c.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [36]:
# Creating array with floating point values
d = np.array([[1,2,3],[4,5,6]],dtype=float)
print(d)

[[1. 2. 3.]
 [4. 5. 6.]]


Initial placeholders in numpy arrays

In [37]:
# Create numpy array of zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
# create numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [39]:
# array of a particular value
z = np.full((5,4),5) #np.full((rows x columns), value)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [42]:
# create identity matrix : all diagonal value will be 1 and other 0
# in identity matrix the number of rows and columns are always equal
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [44]:
# create numpy array with random values
# values will be between 0 to 1
b = np.random.random((3,4))
print(b)

[[0.18482578 0.63765263 0.10150314 0.13397682]
 [0.72465007 0.98802471 0.39990904 0.02203821]
 [0.84789414 0.36008288 0.88656573 0.19100654]]
